---
- name: "update apt package."
  become: yes
  apt:
    update-cache: yes

- name: "upgrade apt package."
  become: yes
  apt:
    upgrade: "yes"

- name: "install nodejs."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: "pm2"
    global: yes
    production: yes
    state: present

- name: "set environment variables"
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-devops.cdf8vxstsstl.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: Udapeople12345!
    TYPEORM_DATABASE: udapeople-devops

