---
- name: Creates directory
  file:
    path: ~/web
    state: directory

- name: Copy Files
  template:
    src: "deploy/files/"
    dest: "~/web/"

- name: Executing node
  shell: |
    pm2 start ~/web/main.js -f